config/routes.rb
SampleApp::Application.routes.draw do

  root to: "static_pages#home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup' => 'users#new'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete
  
  match '/help' => 'static_pages#help'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/sandbox' => 'static_pages#sandbox'

 

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password     # => Adds methods to the class?
  
  validates(:name,    presence: true,
                      length: { maximum: 50 })
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email,   presence: true, 
                      format: { with: valid_email_regex },
                      uniqueness: { case_sensitive: false })
  validates :password, presence:true       
  
  before_save :create_remember_token		# callback, runs method

  private
  	
  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end
  
                 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper 	# see below
end

# By default, helpers are available in the views but not 
# in the controllers. We need the methods from the Sessions helper 
# in both the view and the controllers, so we have to include
# it explicitly.

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			# create error message and re-render sign in form
			# flash.now specifically for rendered pages, contents disappear
			# with an additional request
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	before_filter :signed_in_user,  only: [:sandbox]

	def home
	end

	def help
	end

	def about 
	end

	def sandbox
		@items = [[1,2,3,4], [5,6,3], [3,4,5,6,7,4]]
	end
    
	private

		def signed_in_user
		  unless signed_in?
		    redirect_to signin_url, notice: "Please sign in to access this page." 
		  end
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user,  only: [:index, :edit, :update]
  before_filter :correct_user,    only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])   # => SEE BELOW for params notes
    if @user.save
      sign_in @user
      flash[:success] = "Thanks for signing up!"
      redirect_to @user
    else
      render 'new'
    end
  end

 # def edit
 #   @user = User.find(params[:id])   # => No longer need this with before_filter
 # end

  def update
   # @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = 'Profile updated'
      sign_in @user     # => Need to sign in again because remember_token
      redirect_to @user # => gets reset
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def index
    WillPaginate::per_page = 5
    @users = User.paginate(page: params[:page])
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in." 
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
  
end


# the params hash contains information about each request.
# in the case of a URI like /users/1, the value of params[:id] is 
# the id of the corresponding user (1 in this example). 
#
# In the case of posting to the signup form, params instead contains a 
# hash of hashes. 
#
# Although the hash keys appear as strings in the debug output, 
# internally Rails uses symbols, so that params[:user] is the hash of 
# user attributes—in fact, exactly the attributes needed as 
# an argument to User.new. 
#
# This means that the line @user = User.new(params[:user])
# Is equivalent to
# @user = User.new(name: "Foo Bar", email: "foo@invalid",
#                  password: "dude", password_confirmation: "dude")

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("logo.png", alt: "Sample App", class: "round")
  end
  
  def full_title(page_title)        # => returns the full title on a per-page basis
    base_title = "Ruby on Rails Sample App"
    if page_title.empty? 
      base_title 
    else
     "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in?
		!current_user.nil?		# if current_user is not nil
	end

	def sign_out
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end

	def store_location
		session[:return_to] = request.fullpath
	end

	private

		def user_from_remember_token
			remember_token = cookies[:remember_token]
			User.find_by_remember_token(remember_token) unless remember_token.nil?
		end

		def clear_return_to
			session.delete(:return_to)
		end
end
# cookies is an object??
# using the default method on cookies, sets the expiry to 20 yrs 
# cookies[:remember_token] = { :value   => user.remember_token,
#                             expires: 20.years.from_now.utc }

# current_user is available in both controllers and views

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # => Gravatar URIs are based on an MD5 hash of the user’s email address. In Ruby, the MD5 hashing algorithm is implemented using the hexdigest method, which is part of the Digest library

  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://www.chrismicklethwaite.com" target="_blank">chrismicklethwaite.com</a>
	</small>
	<nav>
		<ul>
		  <li><%= link_to "About", about_path %></li>
		  <li><%= link_to "Contact", contact_path %></li>
		  <li><a href="http://www.ruby-lang.org/en/" target="_blank">Ruby ref</a></li>
		  <li><a href="http://api.rubyonrails.org/" target="_blank">Rails API</a></li>
   		</ul>
   	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="container">
          <%= link_to "Rails sandbox", root_path, id: "logo" %>
          <!-- <%= link_to logo, root_path %> -->
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Sandbox", sandbox_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account<b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
      </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
 	  <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
    
      <%= yield %>
      
      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    
     
    </div> 
    <%= @current_user.name if signed_in? %>
  </body>
</html> 

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			This form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
<h1>About</h1>
<p>
  This is the about us page.</a>

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact us') %>
<h1>Contact</h1>
<p>
  This is the contact us page.</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is the help page</a>

</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class='center hero-unit'>
	<h1>Home</h1>
	<p>This is the home page</p>
	<% if !signed_in? %>
		<%= link_to "Create account", signup_path, class: "btn btn-large btn-primary" %>
	<% end %>
</div>

app/views/static_pages/sandbox.html.erb
<% provide(:title, 'Sandbox') %>
<p>Alternate CSS classes for even and odd numbers...</p>
<table>
<% @items.each do |item| %>
  <tr class="<%= cycle("even", "odd") -%>">
      <% item.each do |value| %>
        <span style="color:<%= cycle("#333", "#666", "#999", :name => "colors") -%>">
          <%= value %>
        </span>
      <% end %>

      <% reset_cycle("colors") %>
  </tr>
<% end %>
</table>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(@user) do |f| %>
    <!--  When constructing a form using form_for(@user), 
          Rails will use POST if @user.new_record? is true and
          PUT if it is false. -->
      <%= render 'shared/error_messages' %>  

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

    <% end %>
    <%= gravatar_for(@user) %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

<!-- shared partials should reside in /views/shared by convention -->

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
  	<%# this calls the _user partial - %>
  	<%= render user %>

  	<%# this would use the users 'collection'. Rails knows and 
  	automatically iterates through- however WillPaginate::per_page
  	set in the controller, seems to be ignored with this %>
  	<%# <%= render @users %>

  <% end %>
</ul>


<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>   <!-- renders the shared partial-->
      
      <%= f.label :name %>
      <%= f.text_field :name %>
    
      <%= f.label :email %>
      <%= f.text_field :email %>
    
      <%= f.label :password %>
      <%= f.password_field :password %>
    
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

<!-- shared partials should reside in /views/shared by convention -->

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= gravatar_for @user, size: 40 %>
				<%= @user.name %><h1>
		</section>
		<strong>Name</strong>	<%= @user.name %><br />
		<strong>Profile</strong>	<%= link_to user_path(@user), @user %>
	</aside>
</div>